version: "3.3"
services:
  dns:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: dns:latest
    environment:
      - PORT=3002
      - VERSION=v1
      - SECTOR_ID=1
    ports:
      - 3001:3002